Demo/Demo.swift
Demo/SceneController.swift

When migrating from turbo-ios, `visitableDidFailRequest(_:error:retryHandler:)` was left behind. This PR adds that back in which fixes the authentication flow when hitting a 401.

Fix authentication flow in demo app

---

Source/Turbo/Navigator/Navigator.swift

`parameters` argument is missing [here](https://github.com/hotwired/hotwire-native-ios/blob/3ba9441959ead175e7b5220abbaf8f18a79bff72/Source/Turbo/Navigator/Navigator.swift#L50). This causes `parameters` not being retained in `handle(proposal: VisitProposal)`.
````swift
// For example, parameters passed in below function call
navigator.route(
rootUrl.appendingPathComponent("/auth/enter-otp"),
options: VisitOptions(action: .advance),
parameters: ["mobileNumber": enternedMobileNumber]
)
extension SceneDelegate: NavigatorDelegate {
func handle(proposal: VisitProposal) -> ProposalResult {
// are not received here in proposal.parameters
}
}
````
It was added in this [commit](https://github.com/hotwired/hotwire-native-ios/commit/958fcd8bb9e6ca4005822cd39374caf0828d5c6a#diff-48abac57e64de24f576c38 …

Fix parameters in route

---

Source/Turbo/Navigator/Navigator.swift

This PR exposes `reload()` on the main `Session`. When working with tabs, it's helpful to be able to manually reload screens after the user signs in or out.

Expose `Session.reload()` on Navigator

---

Source/Turbo/Navigator/Navigator.swift

Hi 👋 
We have several mobile apps that are built using turbo-ios.   
In all of them we extensively use a custom `NativeBridge` class that at its core evaluates JS in the WebView to communicate with the JS side.   
Very stripped down, it looks like this:    
```swift
class NativeBridge: NSObject {
let delegate: NativeBridgeDelegate
var webView: WKWebView?
// MARK: Setup
init(delegate: NativeBridgeDelegate) {
self.delegate = delegate
}
func setWebView(webView: WKWebView) {
self.webView = webView
}
// MARK: Native -> JS
public func postNativeToJS(action: NativeToJSAction, payload: [String:Any]? = nil) {
let actionString = action.rawValue
var payloadString = try? payload?.encodeDictionary()
payloadString = payloadString != nil ? "'\(payloadString!)'" : "null"
let script = …
```

Expose the currently active WebView

---

Source/Turbo/Navigator/Extensions/VisitProposalExtension.swift

This PR addresses a mistake noticed by @mrfidgety in the [turbo-ios repo](https://github.com/hotwired/turbo-ios/pull/158#pullrequestreview-2329794028). We were looking for the `animated` flag in the `parameters` but it should appear in `properties` because it comes from the path configuration.
This PR fixes that typo.

Fix `animated` flag from path configuration

---

Demo/AppDelegate.swift
Demo/SceneController.swift
Source/Bridge/UserAgent.swift
Source/Hotwire.swift
Source/HotwireConfig.swift
Tests/Bridge/UserAgentTests.swift

Brings [Android PR #77](https://github.com/hotwired/hotwire-native-android/pull/77) to iOS, allowing developers to set a custom user agent *prefix* without breaking bridge components or removing "Hotwire Native".
Developers can set a custom `applicationUserAgentPrefix` for their application via:
```swift
Hotwire.config.applicationUserAgentPrefix = "My Application Prefix;"
```
Whenever a `WKWebView` instance is created, the library will now automatically include:
- Your (optional) custom `applicationUserAgentPrefix`
- "Hotwire Native iOS; Turbo Native iOS;"
- "bridge-components: [your bridge components];"
`WKWebView`'s default user agent will also be added to the beginning of the user agent.

Breaking API change: applications can set a User-Agent prefix

---

Source/Hotwire.swift
Source/HotwireConfig.swift

This PR fixes https://github.com/hotwired/hotwire-native-ios/issues/57.

Fix bridge registration

---

Source/Turbo/Session/Session.swift

This resolves the latter part of issue https://github.com/hotwired/hotwire-native-ios/issues/12 where double-requests were being made to the `/success` page after a modal form submission.
To replicate in the demo app:
1. Navigate to "Load a page modally"
2. Tap "Submit Form"
3. Observe that two `/success` `GET` requests are made to the server
Here are the relevant logs:
```
[Bridge] ← formSubmissionStarted ["timestamp": 1734382774207, "location": http://localhost:45678/new]
[Bridge] ← formSubmissionFinished ["location": http://localhost:45678/new, "timestamp": 1734382774231]
[Bridge] ← visitProposed ["options": {
action = advance;
response =     {
redirected = 1;
responseHTML = "<!DOCTYPE html>\n<html lang=\"en\">\n  <head>\n    <meta charset=\"utf-8\">\n    <meta name=\"viewport\" …
```

Fix double-visits after modal form submission redirects

---

Source/Turbo/WebView/turbo.js

This addresses the double-visit request issue found in #12. It works with the new adapter function in core `turbo.js` added here: https://github.com/hotwired/turbo/pull/1354
The root issue is that link taps on iOS are triggering the `mouseenter` and `mouseleave` events used to activate link prefetching. This theoretical optimization actually creates wasteful `GET` requests across the `default` and `modal` context `WKWebView` instances.

Disable link prefetching via the turbo js adapter to prevent double-visit requests

---

Source/Turbo/Navigator/Navigator.swift
Source/Turbo/Networking/RedirectHandler.swift
Source/Turbo/Session/Session.swift
Source/Turbo/Session/SessionDelegate.swift
Source/Turbo/Visit/ColdBootVisit.swift
Source/Turbo/Visit/JavaScriptVisit.swift
Source/Turbo/WebView/ScriptMessage.swift
Source/Turbo/WebView/WebViewBridge.swift
Source/Turbo/WebView/turbo.js
Tests/Turbo/Test.swift

This PR is the counterpart of the Android https://github.com/hotwired/hotwire-native-android/pull/82. 
Due to CORS restrictions, the javascript Fetch API cannot be reliably used across applications to detect cross-origin redirects during Turbo visits.
This new approach hands off failed visits with a non-HTTP status code (which suggests a cross-origin redirect may have been attempted) to the native code to detect cross-origin redirects. If a visit redirect is detected, the final redirect location is treated as an external URL and opened appropriately.

Detect cross-origin redirects during visits

---

Source/Turbo/Visit/ColdBootVisit.swift

This PR addresses https://github.com/hotwired/hotwire-native-ios/issues/78 by ensuring that only top-level navigations are subject to cross-origin redirect checks, while allowing iframe and sub-frame navigations to proceed without interference.
This prevents unwanted redirects from embedded content (e.g., YouTube iframes) while maintaining normal navigation behaviour in the parent frame.

Ignore cross-origin redirects that aren’t happening in the main frame

---

Source/Turbo/Navigator/NavigationHierarchyController.swift
Tests/Turbo/Navigator/NavigationHierarchyControllerTests.swift

This PR fixes an issue when you're in the `modal` context and a visit is proposed to the `default` context. If that visit proposal contains a `replace` action, we don't want to both dismiss the modal screen *and* then `replace` the underlying `default` context screen. That can lead to replacing the `default` context screen that should be preserved, such as the root destination.
The only scenario where we'll both dismiss the modal screen and `replace` is if the underlying `default` context is the same URL as the proposed URL.

Improved `default` context visit behavior when dismissing the `modal` context

---

Source/Turbo/Session/Session.swift

This PR attempts to address #94.
The modal refresh occurred because the `viewWillAppear` method gets triggered even when the modal was already presented and only a minor height adjustment is made (via the short pull-to-refresh gesture).
There's nothing inherently wrong here, but the [context check for the view appearance](https://github.com/hotwired/hotwire-native-ios/blob/main/Source/Turbo/Session/Session.swift#L231-L282) misinterpreted this appearance as navigating backward from a native screen to a web view.   
With the pull-to-refresh gesture, we mistakenly entered [this if check inside the context check](https://github.com/leonvogt/hotwire-native-ios/blob/1ab960be5bd957284fda8bc2085e715a41c990e9/Source/Turbo/Session/Session.swift#L283-L286):
```swift
// Navigating backward from a …
```

Fix unexpected modal refreshes

---

Source/HotwireNavigationController.swift
Source/Turbo/Visitable/VisitableViewController.swift

This PR builds on top of https://github.com/hotwired/hotwire-native-ios/pull/91.
It introduces explicit appear and disappear reasons when presenting/dismissing a modal. Even though the new reasons are currently not used anywhere, I think it makes sense to be explicit.
This PR also addresses https://github.com/hotwired/hotwire-native-ios/issues/82 by making the `VisitableViewController`'s `appearReason` and `disappearReason` `open`.
NOTE: Since tabs are a heavily used UI pattern, we should consider implementing a Hotwire Native tab bar controller.

Fix unremoved screenshot - feedback

---

Source/Turbo/Visitable/VisitableViewController.swift

context:
- https://github.com/hotwired/turbo-ios/pull/234
- https://discuss.hotwired.dev/t/hotwire-native-ios-prevent-tab-bar-items-from-having-their-title-changed-on-page-load/6284

only update the navigation bar title when loading a page, not the tabs

---

Source/Turbo/Navigator/Extensions/PathPropertiesExtensions.swift
Source/Turbo/Navigator/Extensions/VisitProposalExtension.swift
Source/Turbo/Navigator/NavigationHierarchyController.swift
Source/Turbo/Path Configuration/PathConfiguration.swift
Source/Turbo/Path Configuration/PathRule+ServerRoutes.swift
Tests/Turbo/Fixtures/test-configuration-historical-locations.json
Tests/Turbo/Navigator/NavigationHierarchyControllerHistoricalLocationTests.swift
Tests/Turbo/Navigator/NavigationHierarchyControllerTests.swift
Tests/Turbo/Navigator/TestableNavigationController.swift
Tests/Turbo/PathConfigurationTests.swift
Tests/Turbo/PathRuleTests.swift
Tests/Turbo/Spies/SessionSpy.swift

This PR builds on top of https://github.com/hotwired/hotwire-native-ios/pull/74 and addresses https://github.com/hotwired/hotwire-native-ios/issues/71.
[Turbo Native](https://native.hotwired.dev/reference/navigation#server-driven-routing-in-rails) allows server-driven routing in Rails applications. Previously, developers had to explicitly define these routing rules in the path config. This PR adds default routing rules for server-driven navigation directly into the framework.
- recede, resume and refresh historical location rules (historical location rules) have been added as `PathRule`s.
- historical location rules are now loaded by default whether or not the source of the path config is provided.
- the `NavigationHierarchyController` has been adapted to handle the historical location …

Include default server route rules by default

---

Source/HotwireWebViewController.swift
Source/Turbo/Navigator/NavigationHierarchyController.swift
Source/Turbo/Navigator/Navigator.swift
Source/Turbo/Session/Session.swift
Source/Turbo/Visit/Visit.swift
Source/Turbo/Visitable/Visitable.swift
Source/Turbo/Visitable/VisitableViewController.swift
Tests/Turbo/ColdBootVisitTests.swift
Tests/Turbo/Navigator/NavigationHierarchyControllerTests.swift
Tests/Turbo/Test.swift
Tests/Turbo/VisitableViewControllerTests.swift

This PR adapts the `VisitableViewController` to reflect the current web view page location and matches the reload behaviour with Android.
**Context**
Rails/Hotwire allows a page location change(via redirect or Turbo Frames) without a new visit proposal.
Since the native view controller (`VisitableViewController`) is created with the original URL this change is never reflected (see https://github.com/hotwired/hotwire-native-ios/pull/77).
**Changes**
- `VisitableViewController ` now exposes a `currentVisitableURL` which reflects the associated web view's URL.
- `Visit` uses the `currentVisitableURL` when initialized.
NOTE: The backstack handling hasn't changed. It still relies on the `VisitableViewController`'s  original URL-`visitableURL`.
**Resolving web view's URL**
The …

Reflect current web view page location in `VisitableViewController`

---

Demo/SceneController.swift
Source/NavigationHandler.swift
Source/Turbo/Navigator/Helpers/PathConfigurationIdentifiable.swift
Source/Turbo/Navigator/Helpers/ProposalResult.swift
Source/Turbo/Navigator/NavigatorDelegate.swift
Tests/Turbo/Navigator/NavigationHierarchyControllerTests.swift

This adds an internal parameter name to the new "handle" function signature. I think this makes it a bit easier to understand when implementing the delegate function.

Add internal parameter name to new function

---

Source/Bridge/BridgeDelegate.swift
Tests/Bridge/BridgeDelegate+DestinationTests.swift
Tests/Bridge/TestData.swift

This PR adds a function to `BridgeDestination` to get notified when a component is initialized.

Notify bridge destination when a component is initialized

---

Source/Bridge/bridge.js

This updates the web bridge global to prefer `window.HotwireNative` over `window.Strada`. The corresponding change was made in: **hotwire-native-bridge** `1.2`:
- PR: https://github.com/hotwired/hotwire-native-bridge/pull/7
- Release: https://github.com/hotwired/hotwire-native-bridge/releases/tag/v1.2.0

Update the web bridge reference to match hotwire-native-bridge `v1.2+`

---

Demo/Bridge/FormComponent.swift
Demo/Bridge/MenuComponent.swift
Demo/Bridge/OverflowMenuComponent.swift
Demo/NumbersViewController.swift
Source/Bridge/BridgeComponent.swift
Source/Bridge/BridgeDelegate.swift
Source/NavigationHandler.swift
Source/Turbo/Navigator/Navigator.swift
Source/Turbo/Navigator/WKUIController.swift
Tests/Bridge/BridgeComponentAsyncAPITests.swift
Tests/Bridge/BridgeComponentTests.swift
Tests/Bridge/Spies/BridgeDelegateSpy.swift
Tests/Turbo/Navigator/NavigationDelegateTests.swift

This PR refactors the code by using `weak` instead of `unowned` references for delegates.
**Context**
Using `unowned` assumes that the referenced object will always exist, which may not be the case. If the referenced object is accessed after it has been deallocated, the app crashes.
The most common source of crashes is within `BridgeComponent`s due to their unpredictable lifecycles. By using a weak reference instead, we avoid this crash and throw and error.

Use `weak` instead of `unowned` references for delegates

---

Source/Turbo/Navigator/Extensions/VisitProposalExtension.swift
Source/Turbo/Navigator/NavigationHierarchyController.swift
Source/Turbo/Navigator/Navigator.swift
Source/Turbo/Visit/VisitResponse.swift

This is a feedback PR for https://github.com/hotwired/hotwire-native-ios/pull/154.
Changes
- Exposes `VisitResponse` initializer.
- Adds convenience `isRedirect` var to `VisitProposal` extension.
- Handles redirect in the same way as cross origin redirect is handled - popping the current destination from the backstack.

Modal redirects feedback

---

Demo/SceneController.swift

This PR works with [#69 on the demo app](https://github.com/hotwired/hotwire-native-demo/pull/69) to reimplement the authentication flow.
The only real change is popping a controller off of the stack before presenting the `/session/new` route. Most of the code is in the other PR.
https://github.com/user-attachments/assets/c6ea1423-66b0-4108-8fc0-31ae665afb3a

Bring back the authentication flow

---

Demo/AppDelegate.swift
Source/HotwireConfig.swift
Source/Turbo/Navigator/Extensions/UINavigationControllerExtension.swift

This PR animates `replace` actions with a subtle fade animation. It is disabled by default and can be enabled with the following configuration option:
```swift
Hotwire.config.animateReplaceActions = true
```
https://github.com/user-attachments/assets/5448a328-0f48-4f5e-a9a9-d22a299487d4
https://github.com/user-attachments/assets/6a7d1693-6e59-4c45-a114-fef5cd1b3911
Closes #162.
---
I tested through the demo app and the only way this triggers is via the flow shown in the videos above. I couldn't find any other side effects, but would love to know if folks can identify any.

Animate replace actions with a fade animation

---

Source/Turbo/Navigator/Extensions/VisitProposalExtension.swift
Source/Turbo/Navigator/NavigationHierarchyController.swift
Source/Turbo/Visit/VisitResponse.swift
Tests/Turbo/VisitOptionsTests.swift

This PR handles the issue described in #112.
Previously, when an endpoint redirected from a non-modal screen to a modal screen, the presenting view controller was left on the main stack. Empty.
This PR checks for the `.replace` navigation action and if it is the first modal screen on the stack, pops the underlying (redirected _from_) view controller on the main stack.
I tested a few use-cases here but I'm sure there are some flows that I missed. Any help finding these would be greatly appreciated!
Fixes #112

Pop presenting controller if redirected to modal
